### ISSUE TITLE
Strut direction context menu items throw NPE for antiprism symmetry in Polygon7 field  using vZome 7.0.59.

### ISSUE THREAD

**Issue by david-hall** [vZome/vzome#422]
In the polygon7 field with antiprism symmetry, the strut direction context menu throw an NPE at org.vorthmann.zome.ui.DocumentFrame$2.actionPerformed(DocumentFrame.java:372) for all menu items except "Used in Model". 

The context menu correctly works in the polygon7 field with octahedral symmetry and in the golden field with icosa symmetry. I didn't try any other fields or symmetries.

This is a new bug in 7.0.59. It works correctly in 7.0.58.

**Comment by vorth** [comment]
David and I tested on a screenshare and concluded that the issue was only in his dev environment, not in the packaged app, and not in my dev environment on the same commit.
